import OpenAI from 'openai';
import type { Question, Subject, Difficulty } from '../types';
import { getSecureApiKey } from './security';
import { generateAIQuiz } from './ai';

export const validateQuestions = (data: unknown, count: number): Question[] => {
  if (!Array.isArray(data)) {
    throw new Error('AI response is not a valid array');
  }

  const validQuestions: Question[] = [];

  for (let i = 0; i < data.length; i++) {
    const item = data[i];
    if (
      item &&
      typeof item.question === 'string' &&
      Array.isArray(item.options) &&
      item.options.length === 4 &&
      typeof item.correctAnswer === 'number' &&
      item.correctAnswer >= 0 &&
      item.correctAnswer <= 3
    ) {
      validQuestions.push({
        id: item.id || `q_${Date.now()}_${i}`,
        question: item.question.trim(),
        options: item.options.map((opt: string) => String(opt).trim()),
        correctAnswer: item.correctAnswer,
        explanation: typeof item.explanation === 'string' ? item.explanation : undefined,
      });
    }
  }

  if (validQuestions.length === 0) {
    throw new Error('No valid questions generated by AI');
  }

  return validQuestions.slice(0, count);
};

export const generateQuestionsWithAI = async (
  subject: Subject,
  difficulty: Difficulty,
  count: number,
  customApiKey?: string
): Promise<Question[]> => {
  const apiKey = customApiKey || getSecureApiKey() || import.meta.env.VITE_OPENAI_API_KEY || '';

  if (apiKey && apiKey.startsWith('sk-')) {
    try {
      const openai = new OpenAI({
        apiKey: apiKey,
        dangerouslyAllowBrowser: true
      });

      const prompt = `Generate ${count} high-quality, multiple-choice questions for the subject "${subject}" at "${difficulty}" difficulty.
Format as strict JSON array:
[
  {
    "id": "q1",
    "question": "Question text?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswer": 0,
    "explanation": "Brief solution explanation."
  }
]`;

      const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'You return only JSON arrays of quiz questions. No markdown wrap.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.7,
      });

      const content = response.choices[0]?.message?.content || '';
      const cleanJson = content.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);

      return validateQuestions(parsed, count);
    } catch (err: unknown) {
      console.warn('OpenAI API request failed, falling back to secondary generator engine:', err);
    }
  }

  return generateAIQuiz(subject, difficulty, count);
};
