import OpenAI from 'openai';
import type { Question, Subject, Difficulty } from '../types';
import { getSecureApiKey } from './security';
import { generateAIQuiz } from './ai';

export const validateQuestions = (data: unknown, count: number): Question[] => {
  if (!Array.isArray(data)) {
    throw new Error('AI response is not a valid array');
  }

  const validQuestions: Question[] = [];

  for (let i = 0; i < data.length; i++) {
    const item = data[i];
    if (
      item &&
      typeof item.question === 'string' &&
      Array.isArray(item.options) &&
      item.options.length === 4 &&
      typeof item.correctAnswer === 'number' &&
      item.correctAnswer >= 0 &&
      item.correctAnswer <= 3
    ) {
      validQuestions.push({
        id: item.id || `q_${Date.now()}_${i}`,
        question: item.question.trim(),
        options: item.options.map((opt: string) => String(opt).trim()),
        correctAnswer: item.correctAnswer,
        explanation: typeof item.explanation === 'string' ? item.explanation : undefined,
      });
    }
  }

  if (validQuestions.length === 0) {
    throw new Error('No valid questions generated by AI');
  }

  return validQuestions.slice(0, count);
};

export const generateQuestionsWithAI = async (
  subject: Subject,
  difficulty: Difficulty,
  count: number,
  customApiKey?: string
): Promise<Question[]> => {
  const apiKey =
    customApiKey ||
    getSecureApiKey() ||
    import.meta.env.VITE_CHATGPT_API_KEY ||
    import.meta.env.VITE_OPENAI_API_KEY ||
    '';

  if (apiKey && apiKey.startsWith('sk-')) {
    try {
      const openai = new OpenAI({
        apiKey: apiKey,
        dangerouslyAllowBrowser: true,
      });

      const seed = Math.floor(Math.random() * 10000);
      const prompt = `"${subject}" mavzusida va "${difficulty}" qiyinchilik darajasida ${count} ta ko'p variantli (multiple-choice) qiziqarli test savollarini hamda javoblarni strictly O'ZBEK TILIDA yaratib ber (Tasodifiy urug': ${seed}).
Format STRICT JSON array:
[
  {
    "id": "q1",
    "question": "Savol matni O'zbek tilida?",
    "options": ["Variant A O'zbekcha", "Variant B O'zbekcha", "Variant C O'zbekcha", "Variant D O'zbekcha"],
    "correctAnswer": 0,
    "explanation": "Qisqa tushuntirish O'zbek tilida."
  }
]`;

      const response = await openai.chat.completions.create({
        model: 'gpt-4o-mini',
        messages: [
          { role: 'system', content: 'You return only valid JSON arrays of quiz questions in Uzbek. No markdown code blocks.' },
          { role: 'user', content: prompt }
        ],
        temperature: 0.85,
      });

      const content = response.choices[0]?.message?.content || '';
      const cleanJson = content.replace(/```json/g, '').replace(/```/g, '').trim();
      const parsed = JSON.parse(cleanJson);

      return validateQuestions(parsed, count);
    } catch (err: unknown) {
      console.warn('OpenAI API soʻrovi muvaffaqiyatsiz boʻldi, ikkinchi AI motoriga oʻtildi:', err);
    }
  }

  return generateAIQuiz(subject, difficulty, count);
};
